dist: trusty
language: python

services:
  - docker

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
    - python: 2.7
      env: TOXENV=py27

install:
  - git clone https://github.com/rxu18/vertica-testenv.git
  - cd vertica-testenv
  - ./vertica_testenv start
script:
  - ./vertica_testenv test --py $TOXENV
